"""
Export Manager for Simulation Studio.

Handles copying and zipping result files generated by simulation runs.
Follows OOP principles and provides easy-to-use export methods.
"""

import shutil
import zipfile
from pathlib import Path
from typing import List, Optional


class ExportManager:
    """Manager for exporting simulation result files and logs."""

    @staticmethod
    def copy_results(files: List[Path], dest_dir: Path) -> bool:
        """Copy multiple files to a destination directory.

        Args:
            files: List of Path objects to copy.
            dest_dir: Destination directory Path.

        Returns:
            True if all files copied, else False.
        """
        try:
            dest_dir.mkdir(parents=True, exist_ok=True)
            for file in files:
                if file.exists():
                    shutil.copy2(file, dest_dir / file.name)
            return True
        except (OSError, shutil.Error):
            return False

    @staticmethod
    def create_zip(files: List[Path], zip_path: Path) -> bool:
        """Create a ZIP archive containing the specified files.

        Args:
            files: List of Path objects to include in the ZIP.
            zip_path: Path where the ZIP archive will be created.

        Returns:
            True if ZIP created successfully, else False.
        """
        try:
            zip_path.parent.mkdir(parents=True, exist_ok=True)
            with zipfile.ZipFile(zip_path, 'w', zipfile.ZIP_DEFLATED) as zf:
                for file in files:
                    if file.exists():
                        # Use file.name to avoid absolute path inclusion in zip
                        zf.write(file, arcname=file.name)
            return True
        except (OSError, zipfile.BadZipFile):
            return False


class ExportResult:
    """Container for export operation status."""

    def __init__(self, success: bool, message: str, path: Optional[Path] = None):
        self.success = success
        self.message = message
        self.path = path
