"""
Simulation report generator.

Creates structured text reports after each simulation run,
including execution metadata, timing, and output file listings.
"""

from dataclasses import dataclass, field
from datetime import datetime
from pathlib import Path


@dataclass
class SimulationReport:
    """Data collected during a simulation run for reporting."""
    executable_name: str = ""
    executable_path: str = ""
    start_time: int = 0
    stop_time: int = 0
    status: str = "Unknown"
    return_code: int = -1
    execution_duration: float = 0.0
    output_files: list[str] = field(default_factory=list)
    timestamp: str = field(
        default_factory=lambda: datetime.now().strftime("%Y-%m-%d %H:%M:%S")
    )
    command: str = ""
    error_message: str = ""


class ReportGenerator:
    """Generates and saves structured simulation reports.

    Reports are saved as plain-text files in the project directory
    with timestamped filenames for easy identification.
    """

    def __init__(self, output_dir: str | Path | None = None):
        """Initialize the report generator.

        Args:
            output_dir: Directory to save reports. Defaults to './reports/'.
        """
        if output_dir:
            self._output_dir = Path(output_dir)
        else:
            self._output_dir = Path(__file__).resolve().parent.parent / "reports"
        self._output_dir.mkdir(parents=True, exist_ok=True)

    def generate(self, report: SimulationReport) -> str:
        """Format a simulation report as structured text.

        Args:
            report: SimulationReport dataclass with run data.

        Returns:
            Formatted report string.
        """
        separator = "=" * 60
        thin_sep = "-" * 60

        output_files_section = ""
        if report.output_files:
            file_list = "\n".join(f"    • {f}" for f in report.output_files)
            output_files_section = f"""
{thin_sep}
OUTPUT FILES DETECTED:
{file_list}
"""
        else:
            output_files_section = f"""
{thin_sep}
OUTPUT FILES DETECTED:
    (none detected)
"""

        error_section = ""
        if report.error_message:
            error_section = f"""
{thin_sep}
ERROR DETAILS:
    {report.error_message}
"""

        text = f"""{separator}
     OPENMODELICA SIMULATION REPORT
{separator}

TIMESTAMP:          {report.timestamp}
EXECUTABLE:         {report.executable_name}
PATH:               {report.executable_path}

{thin_sep}
SIMULATION PARAMETERS:
    Start Time:     {report.start_time}
    Stop Time:      {report.stop_time}

{thin_sep}
COMMAND EXECUTED:
    {report.command}

{thin_sep}
EXECUTION RESULTS:
    Status:         {report.status}
    Return Code:    {report.return_code}
    Duration:       {report.execution_duration:.3f} seconds
{output_files_section}{error_section}
{separator}
          Generated by OpenModelica Simulation Runner v2.0
{separator}
"""
        return text

    def save(self, report: SimulationReport) -> str:
        """Generate and save a report to a timestamped file.

        Args:
            report: SimulationReport dataclass with run data.

        Returns:
            Absolute path to the saved report file.
        """
        text = self.generate(report)
        timestamp_slug = datetime.now().strftime("%Y%m%d_%H%M%S")
        filename = f"sim_report_{timestamp_slug}.txt"
        filepath = self._output_dir / filename

        try:
            filepath.write_text(text, encoding="utf-8")
        except OSError as exc:
            raise OSError(f"Failed to save report: {exc}") from exc

        return str(filepath.resolve())
